[project]
name = "knowledge_agent"
version = "0.1.0"
description = "A module for creating and managing knowledge graphs with AI"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    'langchain_openai',
    'langchain-ollama',
    'langchain-community',
    'langchain',
    'gensim',
    'nltk',
    'llama_index',
    'llama-index-vector-stores-chroma',
    'nebula3-python',
    'llama-index-graph-stores-nebula',
    'llama-index-llms-ollama',
    'jinja2',
    'langchain_experimental',
    'unstructured[md]',
    'chromadb',
    'onnxruntime==1.15.0',
    "multiprocess>=0.70.17",
]

[project.urls]
Homepage = "https://github.com/yourusername/knowledge_agent"
Issues = "https://github.com/yourusername/knowledge_agent/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src"]

[tool.hatch.build.targets.sdist]
include = [
    "src",
    "LICENSE.txt",
    "README.md",
]

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]

[tool.pylint.MASTER]
init-hook='import sys; sys.path.append("src")'
